title: BITC University
description: Open Source Degree Hacking
remote_theme: just-the-docs/just-the-docs

# Navigation Logic
search_enabled: true
aux_links:
  "Newlane University": "https://newlane.edu"
  "ACE National Guide": "https://www.acenet.edu/National-Guide/"
